# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ver_1_add_time.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddTime(object):
    def setupUi(self, AddTime):
        AddTime.setObjectName("AddTime")
        AddTime.resize(400, 193)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddTime)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(AddTime)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_exemplarId = QtWidgets.QLineEdit(AddTime)
        self.lineEdit_exemplarId.setObjectName("lineEdit_exemplarId")
        self.horizontalLayout_2.addWidget(self.lineEdit_exemplarId)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(AddTime)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_addTime = QtWidgets.QLineEdit(AddTime)
        self.lineEdit_addTime.setObjectName("lineEdit_addTime")
        self.horizontalLayout.addWidget(self.lineEdit_addTime)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddTime)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddTime)
        self.buttonBox.accepted.connect(AddTime.accept)
        self.buttonBox.rejected.connect(AddTime.reject)
        QtCore.QMetaObject.connectSlotsByName(AddTime)

    def retranslateUi(self, AddTime):
        _translate = QtCore.QCoreApplication.translate
        AddTime.setWindowTitle(_translate("AddTime", "Продлить"))
        self.label.setText(_translate("AddTime", "ID экземпляра: "))
        self.label_2.setText(_translate("AddTime", "Доб. время\n"
"(в днях)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddTime = QtWidgets.QDialog()
    ui = Ui_AddTime()
    ui.setupUi(AddTime)
    AddTime.show()
    sys.exit(app.exec_())
