# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ver_1_reg_exemplar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterExemplar(object):
    def setupUi(self, RegisterExemplar):
        RegisterExemplar.setObjectName("RegisterExemplar")
        RegisterExemplar.resize(519, 186)
        font = QtGui.QFont()
        font.setPointSize(9)
        RegisterExemplar.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(RegisterExemplar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(RegisterExemplar)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_exemplarId = QtWidgets.QLineEdit(RegisterExemplar)
        self.lineEdit_exemplarId.setObjectName("lineEdit_exemplarId")
        self.horizontalLayout_3.addWidget(self.lineEdit_exemplarId)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(RegisterExemplar)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_bookID = QtWidgets.QLineEdit(RegisterExemplar)
        self.lineEdit_bookID.setObjectName("lineEdit_bookID")
        self.horizontalLayout_2.addWidget(self.lineEdit_bookID)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(RegisterExemplar)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(RegisterExemplar)
        self.buttonBox.accepted.connect(RegisterExemplar.accept)
        self.buttonBox.rejected.connect(RegisterExemplar.reject)
        QtCore.QMetaObject.connectSlotsByName(RegisterExemplar)

    def retranslateUi(self, RegisterExemplar):
        _translate = QtCore.QCoreApplication.translate
        RegisterExemplar.setWindowTitle(_translate("RegisterExemplar", "Зарег. экземпляр"))
        self.label_2.setText(_translate("RegisterExemplar", "ID экземпляра: "))
        self.label.setText(_translate("RegisterExemplar", "ID книги: "))
        self.lineEdit_bookID.setToolTip(_translate("RegisterExemplar", "<html><head/><body><p>Введите ID книги, экземпляр которой хотите зарегистрировать</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterExemplar = QtWidgets.QDialog()
    ui = Ui_RegisterExemplar()
    ui.setupUi(RegisterExemplar)
    RegisterExemplar.show()
    sys.exit(app.exec_())
