# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ver_1_take_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TakeBook(object):
    def setupUi(self, TakeBook):
        TakeBook.setObjectName("TakeBook")
        TakeBook.resize(500, 110)
        self.verticalLayout = QtWidgets.QVBoxLayout(TakeBook)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_6.setSpacing(24)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(TakeBook)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_exemplarID = QtWidgets.QLineEdit(TakeBook)
        self.lineEdit_exemplarID.setObjectName("lineEdit_exemplarID")
        self.horizontalLayout_6.addWidget(self.lineEdit_exemplarID)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.buttonBox = QtWidgets.QDialogButtonBox(TakeBook)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TakeBook)
        self.buttonBox.accepted.connect(TakeBook.accept)
        self.buttonBox.rejected.connect(TakeBook.reject)
        QtCore.QMetaObject.connectSlotsByName(TakeBook)

    def retranslateUi(self, TakeBook):
        _translate = QtCore.QCoreApplication.translate
        TakeBook.setWindowTitle(_translate("TakeBook", "Вернуть книгу"))
        self.label_5.setText(_translate("TakeBook", "ID экземпляра"))
        self.lineEdit_exemplarID.setToolTip(_translate("TakeBook", "<html><head/><body><p>Введите ID экземпляра данной книги</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TakeBook = QtWidgets.QDialog()
    ui = Ui_TakeBook()
    ui.setupUi(TakeBook)
    TakeBook.show()
    sys.exit(app.exec_())
